server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    redis:
      time-to-live: 600000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  liquibase:
    enabled: true
    change-log: config/liquibase/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: dadayevjahongir82@gmail.com
    password: {PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    token:
      secret-key: 404E635266556A586E3272357538782F413F442A472D4B6150645367566B5970
      expiration-time: 3600000